#We can raise exceptions using the raise keyword

print(1)
raise ValueError
print(2)
